<?php
require('../set.php');
session_start();
if(!isset($_SESSION['id'])  ||  $_SESSION['role']!=="admin"){
  header('Location: ../Authentification/');
}




// Fetch products from the database
$sql = "SELECT * FROM `product`"; // Use the correct table name for products
$result = mysqli_query($conn, $sql);

$products = array(); // An array to store product data

if (mysqli_num_rows($result) > 0) {
    while ($row = mysqli_fetch_assoc($result)) {
        $products[] = $row;
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <style>
        /* CSS to hide the divs by default */
        #Product div {
            display: none;
        }
        #societe {
            display: block;
        }
        #Product p{
            color: red;
            font-weight: bold;
        } 
.text-shadow-drop-center {
    -webkit-animation: text-shadow-drop-center 0.6s infinite both;
            animation: text-shadow-drop-center 0.6s infinite both;
}

/* ----------------------------------------------
 * Generated by Animista on 2023-9-28 1:47:11
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * @animation text-shadow-drop-center
 * ----------------------------------------
 */
@-webkit-keyframes text-shadow-drop-center {
  0% {
    text-shadow: 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    text-shadow: 0 0 18px rgba(0, 0, 0, 0.35);
  }
}
@keyframes text-shadow-drop-center {
  0% {
    text-shadow: 0 0 0 rgba(0, 0, 0, 0);
  }
  100% {
    text-shadow: 0 0 18px rgba(0, 0, 0, 0.35);
  }
}

    </style>
<link rel="stylesheet" href="css/style.min.css">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible"
          content="IE=edge">
    <meta name="viewport"
          content="width=device-width,
                   initial-scale=1.0">
    <title>netserv</title>
    <link rel="stylesheet"
          href="css/style.css">

	<style type="text/css">
        body{
            text-align: justify;
        }
     td,th{
        padding: 10px 30px;
     }   
    </style>
</head>
 
<body>

    <header>
 
        <div class="logosec">
            <div class="logo">NETSERV</div>
            <img src=
"https://media.geeksforgeeks.org/wp-content/uploads/20221210182541/Untitled-design-(30).png"
                class="icn menuicn"
                id="menuicn"
                alt="menu-icon">
        </div>
 
        <div class="message">
            <div class="dp">
              <img src="../../imgUser/<?=$_SESSION['img']?>"
                    class="dpicn"
                    alt="dp">
              </div>
        </div>
 
    </header>
 
    <div class="main-container">
        <div class="navcontainer">
            <nav class="nav">
                <div class="nav-upper-options">
                    <a href="index.php" style="all:unset;"><div class="nav-option option2">
                        <img src="img/dashboard.jpg"
                            class="nav-img"
                            alt="dashboard">
                        <h3> Dashboard</h3>
                    </div></a>
                    <a href="devis.php" style="all:unset;"><div class="nav-option option1">
                        <img src="img/message.png"
                            class="nav-img"
                            alt="dashboard">
                        <h3> Ajouter Un devis</h3>
                    </div></a>
                    <a href="devis_manager.php" style="all:unset;"><div class="nav-option option2">
                        <img src="img/message.png"
                            class="nav-img"
                            alt="dashboard">
                        <h3> Devis manager</h3>
                    </div></a>
 
                    <a href="edit_profile_admin.php" style="all:unset;"><div class="nav-option option2">
                        <img src="img/edit.jpg" class="nav-img" alt="settings">
                        <h3> Settings</h3>
                    </div></a>

                    <a href="../deconnexion.php" style="all:unset;">
                        <div class="nav-option logout">
                        <img src="img/logout.jpg" class="nav-img" alt="logout">
                        <h3>Logout</h3>
                    </div></a>
 
                </div>
            </nav>
        </div>
        <div class="main">
            <h2>Kteb smit lproduits li baghi tzid o selectionih mli yban lek</h2>   
                <div id="search">
        <input type="text" id="searchInput" placeholder="kteb hna smit produit" name="">
    </div>
    <div id="show_hide_inputs">
        <?php
        foreach ($products as $product) {
        ?>
        <div class="product-row">
            <label><?=$product['nameP']?></label> <input type="checkbox" name="productCheckbox" data-target="<?=$product['idP']?>">  <br>
        </div>
        <?php }?>
    </div>
    <hr>
    <script>
        $(document).ready(function () {
            // Hide all product rows initially
            $('.product-row').hide();

            $('#searchInput').on('input', function () {
                var searchText = $(this).val().trim().toLowerCase();

                // Hide all product rows
                $('.product-row').hide();

                // Show product rows that have at least one character in common with the search text
                if (searchText !== "") {
                    if (searchText === "*") {
                        // Show all product rows if '*' is entered
                        $('.product-row').show();
                    } else {
                        $('.product-row').each(function () {
                            var label = $(this).find('label').text().toLowerCase();
                            if (label.indexOf(searchText) !== -1) {
                                $(this).show();
                            }
                        });
                    }
                }
            });
        });
    </script>
<form method="POST" action="work.php">
<div id="Product">
<h2>3amer ghi lquantite li ghatn9as</h2>
<p class="text-shadow-drop-center">3andak teghlat makaynx rje3 lor oula ghayjriw 3lek mn charika !!!!!!!</p>   
<?php
    $i = 1; // Reset the counter for each variable product
    $j=1;
foreach ($products as $product) {

    if ($product['hasVariables'] == 0) {
        echo '<div id="' . $product['idP'] . '">';
        echo  "<b>".$product['nameP'] . ' </b>|| Quantite:  <b><u>' . $product['qtyP'] . '</u></b>  PRIX UNITAIRE: <b>'.$product['prixP'] . "DH </b> ";
        echo '<input type="hidden" name="idProduct' . $j . '" value="' . $product['idP'] . '">';
        echo '<input class="custom-input" type="number" min="0" max="' . $product['qtyP'] . '" name="qtyProduct' . $j . '">';
        echo '</div>';
        $j++;
    } else {
        echo '<div id="' . $product['idP'] . '">';
        echo "<b>".$product['nameP'] . "</b> PRIX UNITAIRE: <b>".$product['prixP'] . "DH </b> ".'<br>';
        
        // Check if the product has variables (sizes)
        if ($product['hasVariables'] == 1) {

            // Fetch sizes associated with the current product
            $sql = "SELECT s.idSize, s.sizeValue, pd.qty , pd.idP
                    FROM `size` s
                    LEFT JOIN `product_detail` pd ON s.idSize = pd.idSize AND pd.idP = {$product['idP']} WHERE pd.qty IS NOT NULL";
            $result = mysqli_query($conn, $sql);

            if (mysqli_num_rows($result) > 0) {
                
                while ($size = mysqli_fetch_assoc($result)) {               
                    // Generate size labels and hidden input fields
                    echo '&nbsp;&nbsp;&nbsp;' . $size['sizeValue'] . ' || Quantite: <b><u>' . $size['qty'] . '</u></b>';
                    echo '<input type="hidden" name="idP' . $i . '" value="' . $size['idP'] . '">';
                    echo '<input type="hidden" name="idSize' . $i . '" value="' . $size['idSize'] . '">';
                    
                    // Generate input fields for quantity
                    echo '<input class="custom-input" type="number" min="0" max="' . $size['qty'] . '" name="qty' . $i . '">' . '<br>';
                    
                    $i++;
                }
            }
            echo '</div>';
        }
    }

}

?>
</div>

<script>
    const checkboxes = document.querySelectorAll('input[name="productCheckbox"]');
    const divsToHide = document.querySelectorAll('#Product > div');

    checkboxes.forEach(checkbox => {
        checkbox.addEventListener("change", function() {
            const targetID = this.getAttribute('data-target');
            const targetDiv = document.getElementById(targetID);
            if (targetDiv) {
                targetDiv.style.display = this.checked ? 'block' : 'none';
            }
        });
    });
</script>
<script>
function toggleSociete() {
  var societeDiv = document.getElementById("societe");
  var checkbox = document.getElementsByName("show_hide_societe")[0];
  
  if (checkbox.checked) {
    societeDiv.style.display = "block";
  } else {
    societeDiv.style.display = "none";
  }
}

// Function to set the initial state based on the checkbox
function setInitialState() {
  var societeDiv = document.getElementById("societe");
  var checkbox = document.getElementsByName("show_hide_societe")[0];

  if (checkbox.checked) {
    societeDiv.style.display = "block";
  } else {
    societeDiv.style.display = "none";
  }
}

// Add an event listener to the checkbox to toggle the div
document.addEventListener("DOMContentLoaded", setInitialState);
</script>
</head>
<body>

<label>
  <input type="checkbox" name="show_hide_societe" onchange="toggleSociete()">
  Dakhel  Daba lma3loumat dyal charika Li m9adya devis
</label>

<div id="societe">
  <h2>Societe informations</h2>
  <label for="buyer_name">Nom du Société :</label>
  <input type="text" name="buyer_name" required><br>
  
  <label for="mail_address">Mail Address du Société :</label>
  <input type="email" name="mail_address" required><br>
  
  <label for="phoneNumber">Phone Number du Société :</label>
  <input type="text" name="phoneNumber" required><br>
  
  <label for="company_name">Company Name du Société :</label>
  <input type="text" name="company_name" required><br>
  
  <label for="address">Address du Société :</label>
  <input type="text" name="address" required><br> 
  <hr><br>
</div>
<br>
<hr>
T2aked ou 3awed t2aked: <input type="checkbox" required name="">

<br>

<input type="submit" name="ok">
</form>
        </div>
    <script src="js/script.js"></script>
</body>
</html>
